In [2]:
# does ABC = CAB if all are n-dimensional?
# what if B = transpose(A)?

import numpy as np # get matrices


In [8]:
A = np.mat([1,2,3])
B = np.mat([[4,5,6],[7,8,9],[10,11,12]])
C = (np.mat([13,14,15])).T

In [15]:
print('ABC = {0}'.format(A*B*C))
print('CAB = {0}'.format(C*A*B))
print('BCA = {0}'.format(B*C*A))

ABC = [[2280]]
CAB = [[624 702 780]
 [672 756 840]
 [720 810 900]]
BCA = [[ 212  424  636]
 [ 338  676 1014]
 [ 464  928 1392]]


In [16]:
# now let's have C = A_T

At = A.T

In [17]:
print("ABA' = {0}".format(A*B*At))
print("A'AB = {0}".format(At*A*B))
print("BA'A' = {0}".format(B*At*A))

ABA' = [[336]]
A'AB = [[ 48  54  60]
 [ 96 108 120]
 [144 162 180]]
BA'A' = [[ 32  64  96]
 [ 50 100 150]
 [ 68 136 204]]


In [ ]:
# so the answer is "no silly the dimensions don't even match"
# The multivariate Gaussian likely takes the form (x-u)^T * (cov^-1) * (x-u) to form a scalar
# as the function itself maps to R